########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
    - { name: Tools, url: "tools.html" }

  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
    - { name: Tools, url: "tools.html" }

######################### Default Parameters ###########################

# logo
logo: "/assets/images/logo.svg"
# meta data
author: "WASHWays"
description: "This is meta description"
# google analitycs ID
google_analitycs_id: "" # your id
# contact form action
contact_form_action: "#" # contact form works with : https://formspree.io
# copyright
copyright: "Copyright &copy; 2024 [washways](https://washways.org)"

# preloader
preloader:
  enable: true
  preloader: "" # use png, jpg, svg or gif format

# search
search:
  enable: true

############################## Social Site ##########################
social:

  - name: "github"
    icon: "ti-github" # themify icon pack https://themify.me/themify-icons
    link: "https://github.com/washways/"


